### ISSUE TITLE
Bug but not sure if it's my fault or a problem with this code...

### ISSUE THREAD

**Issue by scottbert** [modufolio/Koken-App#20]
Hi,

I recently used this repo to upgrade Koken as I wanted to move to PHP 8.1.

I've just completed moving it to sit behind nginx.

I'm only using the API, but looking at the admin interface and the public pages for Koken and I seem to have the same issues there as well. Namely, 

```nginx
location ~ "^/storage/cache/images(/(([0-9]{3}/[0-9]{3})|custom)/.*)$" {
  expires max;
  etag off;
  try_files $uri /i.php?path=$1;
}

```
This nginx block is no longer being hit, looking at the API image urls and indeed the images being served in the site, they're all coming from `i.php?/<paths>/<name>.jpg`

The `<domain>/storage/cache/images/etc` urls all work correctly and nginx serves them with no problem so for the time being I'm just rewriting the urls coming out of the API, but I also don't know why this is happening.

Do you have any suggestions as to why this might be?

**Comment by modufolio** [comment]
Hi, sorry for my late reply. 

Unfortunately I have no experience with nginx. Is there a nginx error log where we can find some useful information? Did koken worked correctly on Apache before the migration to nginx?

**Comment by scottbert** [comment]
As far as I'm aware, the original Koken worked fine under apache, and I think it also worked fine under nginx. There appear to be no errors, everything works fine, it's just the images coming back from the API are using `i.php?<query params>` urls and not direct urls to the images as hosted on the file system - do you know how Koken works out the urls? Is there something I need to pass to koken requests to make sure the response is correct or something?

**Comment by baslking** [comment]
FYI, I have one version running on my own  NGINX and PHP 8.2 using php-fpm and one running on Apache with PHP 8.1 on a hosting platform I don't control.   I don't see any clear differences. That information may or may not be useful.
