### ISSUE TITLE
[PHP8.0] Error when uploading photos

### ISSUE THREAD

**Issue by modufolio** [modufolio/Koken-App#8]
Error when uploading image (or via URL). But the image uploads anyway, have to reload the page in the backend to see it there though. Or delete image cache.

**Comment by D4rkPh0en1x** [comment]
The same is with PHP 8.1
If you need that I test something simply let me know

**Comment by modufolio** [comment]
STRICT_TRANS_TABLES was responsible for setting MySQL strict mode and these errors

execute the following if koken is the only database in your mysql server

set global sql_mode='';

**Comment by p4tpr0** [comment]
Hello, 
On my Koken server, the problem persists with current code. Unfortunately I can't set sql_mode to "" on this shared server.
Any idea?

**Comment by modufolio** [comment]
The current codeigniter driver is causing too much problems. I will move to Doctrine DBAL / Laravel Database connection
